.TH SLACK 1 SLACK
.SH NAME
slack - Spawn processes with customised timer slack
.SH SYNOPSIS
.B slack
[-f] ('get' | 'GET' | ('reset' |
.IR interval )
.I command
.RI [ argument ]\ ...)
.SH DESCRIPTION
If the verb 
.B get
or
.B GET
is used, the current timer slack value and exit. If get is used, the
program shall use as high prefix as possible. If
.V GET
is used the value shall be printed in nanoseconds but not unit shall
be printed.
.PP
If the verb reset is used, the process shall set the timer slack value
for the process to the default timer slack value, and
.BR exec (3)
to
.IR command .
.PP
If an
.I interval
is given, the process shall set the timer slack value for the process
to
.IR interval ,
and
.BR exec (3)
to
.IR command .
.PP
.I interval
must be a positive number, optionally with a prefix. Recognised
prefixes (and units) are:
.TP
.BR ns ,\  n
nanoseconds (default)
.TP
.BR µs ,\  µ ,\  us \,\  u
microseconds
.TP
.BR ms ,\  m
milliseconds
.TP
.BR s
seconds
.PP
The default timer slack value is the timer slack value on PID 1.
.SH OPTIONS
.TP
.B \-f
Fail if the timer slack value cannot be set.
.SH NOTES
Real-time threads do not slack around.
.SH RATIONALE
Could be useful increase the performance of your computer.
.SH "SEE ALSO"
.BR nice (1),
.BR ionice (1),
.BR prctl (2)
.SH AUTHORS
Mattias Andrée
.RI < maandree@kth.se >
